services:
  network-deploy-service:
    networks:
      - joaobank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:8.0
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -u root -proot -e 'select 1'" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-eurekaserver-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
