apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: joaotinelli/eurekaserver:s13
          ports:
            - containerPort: 8070
          
          # 1. LOAD CONFIGURATION
          # This pulls in:
          # - SPRING_CONFIG_IMPORT (to find Config Server)
          # - SPRING_RABBITMQ_HOST (to connect to Bus)
          envFrom:
            - configMapRef:
                name: joaobank-configmap
          
          # 2. HEALTH CHECKS
          # Eureka takes a while to register itself and sync.
          # We give it a generous initialDelay.
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8070
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8070
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  # 3. CRITICAL DNS NAME
  # This matches "http://eurekaserver:8070/eureka/" in ConfigMap
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  # LoadBalancer lets access the Eureka Dashboard at http://localhost:8070
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
